#!/usr/bin/env python3
"""Generate src/api/30_choreographies.lua from a Disney Infinity 3.0 install.

    python tools/generate_choreography_catalog.py "D:/.../Disney Infinity 3.0 Gold Edition"

A choreography is named after its archive: assets/choreographies/rr/rr_starbasic.zip
is the "RR_StarBasic" the game passes to PlayAwardCho (eventmanagerdata_game_compiled.lua).
Only the shipped .zip archives are listed, so a hand-edited install cannot leak loose
folders into the catalog. Mods used to scan this folder at run time with io.popen, which
blocks the game thread for seconds; the catalog makes the list free at run time.
"""

from __future__ import annotations

import argparse
import pathlib
import sys

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "api" / "30_choreographies.lua"

HEADER = """-- CrabeLoader
-- File description:
-- Choreographies: the {count} animation names the game ships, and playing one on a player.
-- Generated by tools/generate_choreography_catalog.py from assets/choreographies/*.zip.
-- Lists names only; whether one suits the current hero is up to the engine.
--
-- Authors: @LucasLhomme

Game = Game or {{}}

-- One name per line, lower case like the archives. Kept as one long string and
-- split on first use so the embedded API does not build 7000+ tables at load.
local RAW = [[
{names}
]]

local catalog = nil

--- Returns every choreography name, sorted. The same table on every call: do not modify it.
function Game.ListChoreographies()
    if not catalog then
        catalog = {{}}
        for name in RAW:gmatch("[^\\n]+") do catalog[#catalog + 1] = name end
    end
    return catalog
end

--- Plays a choreography on a player (the host by default). The native takes the
--- player first and the name second, as economy_alert.lua calls it.
function Game.PlayChoreography(name, playerId)
    if type(name) ~= "string" or name == "" then
        error("Game.PlayChoreography: name must be a non-empty string", 2)
    end
    if type(PlayAwardCho) ~= "function" then
        error("Game.PlayChoreography: PlayAwardCho is not available in this Lua state", 2)
    end
    PlayAwardCho(Crabe.hostPlayer(playerId), name)
    return true
end
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("game_dir", type=pathlib.Path)
    args = parser.parse_args()

    root = args.game_dir / "assets" / "choreographies"
    if not root.is_dir():
        print(f"not a Disney Infinity 3.0 install: {root} is missing", file=sys.stderr)
        return 1

    names = sorted({path.stem.lower() for path in root.rglob("*.zip")})
    if not names:
        print(f"no .zip archive under {root}", file=sys.stderr)
        return 1
    if any("]]" in name or "\n" in name for name in names):
        print("a name would break the Lua long string", file=sys.stderr)
        return 1

    OUTPUT.write_text(HEADER.format(count=len(names), names="\n".join(names)), encoding="utf-8", newline="\n")
    print(f"{OUTPUT.relative_to(OUTPUT.parent.parent.parent)}: {len(names)} choreographies")
    return 0


if __name__ == "__main__":
    sys.exit(main())
